### PR TITLE
Upgrade packages to their latest versions

### PR DESCRIPTION
**Pull request by ipeychev**

### CODE REVIEW

**Comment by pragmaticivan** [comment]
Was there any reason you removed the `^`  on the versions?

**Comment by ipeychev** [comment]
Yes - to force NPM to match the version exactly and to try to achieve consistent installs across machines. [Here](https://docs.npmjs.com/cli/shrinkwrap) are more details why locking the version is not a bad idea.
Of course, locking in such a way is not enough to achieve consistent installs - what Yarn does is the right way, but at least it is a step forward.

I'm almost confident this [issue](https://github.com/metal/metal-tools-build-rollup/issues/4) was result of a minor upgrade in the package. Probably when Maira created the test, they were printing in the console "Use of \`eval\`" and Maira added as a test condition this string. Then they changed it and released a new minor upgrade and this change was considered as backward compatible (and it is, since this is not an API, but just a string). However, when I installed it today, the test failed.

**Comment by pragmaticivan** [comment]
Cool, agreed, that's the same approach I used with rubygems. By the ways, looking forward to start having a yarn.lock on all those repos. Thanks.

But, it seems to be a pattern across all the projects. Maybe we should consider talking to Maira and Eduardo about that before merge.

**Comment by ipeychev** [comment]
Yeah, we should consider doing in all the projects.

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/metal/metal-tools-build-rollup/compare/1578bda~0...1578bda) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
