### PR TITLE
Update the expected console message

### PR DESCRIPTION
**Pull request by ipeychev**

### CODE REVIEW

**Comment by brunobasto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunobasto** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/metal/metal-tools-build-rollup/compare/0015760~0...0015760) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pragmaticivan** [comment]
Should we close this one @brunobasto ?

**Comment by brunobasto** [comment]
Hey @ipeychev, I'm closing this one since your fix is merged. We decided to postpone the removal of the ^ in the dependencies until we decide to do it in all projects. See: 38783fd91374e08d60f042513f42bf8154207538

Thanks!

**Comment by ipeychev** [comment]
Okay, Bruno, let's consider to do it across all the projects, that's the right way.

**Pull request closed without merging**
